### ISSUE TITLE
Stereotype Threat

### ISSUE THREAD

**Issue by achen116** [erictflores/erictflores.github.io#1]
Really enjoyed your post, Eric! I appreciate how detailed you were about sharing your experiences with stereotype threat and how you've learn to overcome them. I found it hard for myself to be vulnerable in my own post so just wanted to say good job on letting yourself be open while providing inspiring words for your readers :)

**Comment by erictflores** [comment]
Thanks, Adrienne 8 ).

On Fri, Apr 24, 2015 at 3:14 PM, achen116 <notifications@github.com> wrote:

> Really enjoyed your post, Eric! I appreciate how detailed you were about
> sharing your experiences with stereotype threat and how you've learn to
> overcome them. I found it hard for myself to be vulnerable in my own post
> so just wanted to say good job on letting yourself be open while providing
> inspiring words for your readers :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erictflores/erictflores.github.io/issues/1>.
>



-- 

Eric Flores
LinkedIn <http://www.linkedin.com/in/eflo12>

*"Dream no small dreams for they have no power to move the hearts of men."*
*-Johann Wolfgang von Goethe*
